#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-23"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "5b432028bb2e4feaab147a813a2391ec" }
]
